CREATE TABLE Events (
    ID INTEGER NOT NULL PRIMARY KEY,
    CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    TITLE TEXT NOT NULL,
    START_TIME INTEGER NOT NULL,
    END_TIME DATETIME NOT NULL,
    LOCATION TEXT NOT NULL,
    DESCRIPTION TEXT NOT NULL,
    MAX_ATTENDEES INTEGER NOT NULL,
    MAX_VOLUNTEERS INTEGER,
    COST INTEGER,
    IMAGE BLOB,  
);